version: '3'
services:
  # ubuntu:
  #   build:
  #     context: .
  #     dockerfile: UbuntuDockerfile

  tomcat-app:
    build:
      context: .
      dockerfile: TomcatDockerfile
    ports:
      - "8081:8080"
    networks:
      - tarea-7-network

  mariadb-server:
    build:
      context: .
      dockerfile: MariaDBDockerfile
    ports:
      - "3306:3306"
    networks:
      - tarea-7-network

  cloudbeaver-client:
    build:
      context: .
      dockerfile: CBDockerfile
    ports:
      - "8978:8978"
    networks:
      - tarea-7-network

networks:
  tarea-7-network: